# # venusa_app/urls.py
# from django.urls import path, include
# from rest_framework.routers import DefaultRouter
# from .views import (
#     SearchViewSet, OfferViewSet, CategoryViewSet, AuthViewSet,
#     WishlistViewSet, CartViewSet, DashboardViewSet, OrderViewSet,
#     SuggestionViewSet, ProductDetailViewSet
# )

# app_name = 'venusa_app'

# # Initialize the router
# router = DefaultRouter()

# # Register viewsets
# router.register('search', SearchViewSet, basename='search')
# router.register('offers', OfferViewSet, basename='offers')
# router.register('categories', CategoryViewSet, basename='categories')
# router.register('auth', AuthViewSet, basename='auth')
# router.register('wishlist', WishlistViewSet, basename='wishlist')
# router.register('cart', CartViewSet, basename='cart')
# router.register('dashboard', DashboardViewSet, basename='dashboard')
# router.register('orders', OrderViewSet, basename='orders')
# router.register('suggestions', SuggestionViewSet, basename='suggestions')
# router.register('products', ProductDetailViewSet, basename='products')

# # Define the urlpatterns list explicitly
# urlpatterns = [
#     path('', include(router.urls)),
# ]

# venusa_app/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    SearchViewSet, OfferViewSet, CategoryViewSet, AuthViewSet,
    WishlistViewSet, CartViewSet, DashboardViewSet, OrderViewSet,
    SuggestionViewSet, ProductDetailViewSet
)

router = DefaultRouter()

# Register all viewsets
router.register('search', SearchViewSet, basename='search')
router.register('offers', OfferViewSet, basename='offers')
router.register('categories', CategoryViewSet, basename='categories')
router.register('auth', AuthViewSet, basename='auth')
router.register('wishlist', WishlistViewSet, basename='wishlist')
router.register('cart', CartViewSet, basename='cart')
router.register('dashboard', DashboardViewSet, basename='dashboard')
router.register('orders', OrderViewSet, basename='orders')
router.register('suggestions', SuggestionViewSet, basename='suggestions')
router.register('products', ProductDetailViewSet, basename='products')

# The DefaultRouter automatically includes the API root view
# urlpatterns are properly generated by the router
urlpatterns = router.urls